export const SET_SITE = "SET_SITE";
export const UPDATE_CURRENT_PAGE_SEGMENT = "UPDATE_CURRENT_PAGE_SEGMENT";
export const UPDATE_PAGE_ON_CURRENT_SITE = "UPDATE_PAGE_ON_CURRENT_SITE";
export const SET_CURRENT_PAGE = "SET_CURRENT_PAGE";
