export const SET_SITE = 'SET_SITE';
export const UPDATE_CURRENT_PAGE_SEGMENT = 'UPDATE_CURRENT_PAGE_SEGMENT';
export const SET_CURRENT_PAGE_TO_CURRENT_SITE = 'SET_CURRENT_PAGE_TO_CURRENT_SITE';
export const SET_CURRENT_PAGE = 'SET_CURRENT_PAGE';
export const UPDATE_TITLE_AND_SLUG = 'UPDATE_TITLE_AND_SLUG';
